In [1]:
from mfusampler.main import MfU_control, MfU_sample_run
import numpy as np
from scipy.stats import multivariate_normal

In [10]:
N = 3

x_init = np.repeat(0.0, N)
my_mean = np.random.uniform(-3, 3, N)
my_cov = np.diag(np.random.uniform(1, 2, N))

if N == 3:
    my_cov[0, 1] = my_cov[1, 0] = +0.3

def my_multi(x, mean, cov):
    return np.log(multivariate_normal.pdf(x, mean, cov))

In [11]:
nsmp = int(1e3)
import time

t = time.time()
xsmp = MfU_sample_run(x = x_init, f = my_multi, mean = my_mean, cov = my_cov, nsmp = nsmp)
t = time.time() - t
print(f'elapsed time: {round(t, 1)}sec')

elapsed time: 4.3sec


In [12]:
np.mean(xsmp[(nsmp//2):, :], axis = 0), my_mean

(array([ 0.38531553,  2.04616806, -1.83637794]),
 array([ 0.41140346,  2.04391967, -1.81688819]))

In [13]:
np.cov(xsmp[(nsmp//2):, :].transpose()), my_cov

(array([[ 1.62959205,  0.26806537,  0.09492313],
        [ 0.26806537,  2.0967038 , -0.0378236 ],
        [ 0.09492313, -0.0378236 ,  1.69541374]]),
 array([[1.64380154, 0.3       , 0.        ],
        [0.3       , 1.89545278, 0.        ],
        [0.        , 0.        , 1.67098994]]))