In [1]:
from mfusampler.main import MfU_control, MfU_sample_run
import numpy as np
from scipy.stats import multivariate_normal

In [2]:
N = 3

x_init = np.repeat(0.0, N)
my_mean = np.random.uniform(-3, 3, N)
my_cov = np.diag(np.random.uniform(1, 2, N))

if N == 3:
    my_cov[0, 1] = my_cov[1, 0] = +0.3

def my_multi(x, mean, cov):
    return np.log(multivariate_normal.pdf(x, mean, cov))

In [3]:
nsmp = int(1e4)
import time

t = time.time()
xsmp = MfU_sample_run(x = x_init, f = my_multi, mean = my_mean, cov = my_cov, nsmp = nsmp)
t = time.time() - t
print(f'elapsed time: {round(t, 1)}sec')

elapsed time: 33.9sec


In [4]:
np.mean(xsmp[(nsmp//2):, :], axis = 0), my_mean

(array([ 1.43962806, -1.97491448,  0.99385673]),
 array([ 1.44245065, -1.98101344,  1.01190459]))

In [5]:
np.cov(xsmp[(nsmp//2):, :].transpose()), my_cov

(array([[1.92429905, 0.30062884, 0.00990032],
        [0.30062884, 1.28112648, 0.0032412 ],
        [0.00990032, 0.0032412 , 1.10548165]]),
 array([[1.92873219, 0.3       , 0.        ],
        [0.3       , 1.28599989, 0.        ],
        [0.        , 0.        , 1.16554795]]))